    "m = int(input(\"> 총 건수를 입력하시오: \"))\n",
    "n = int(input(\">한 페이지에 보여줄 게시물 수를 입력하시오: \"))\n",
    "\n",
    "if n <= 0:\n",
    "    print((\"1이상의 수를 입력하시오.\"))\n",
    "    n = int(input(\">한 페이지에 보여줄 게시물 수를 입력하시오: \"))\n",
    "                            \n",
    "if m > n:\n",
    "    output = (m//n) + 1\n",
    "              \n",
    "elif m == n:\n",
    "    output = (m//n)\n",
    "              \n",
    "else:\n",
    "    ouput = (m//n) +1\n",
    "     \n",
    "print(m,n,output)"
